name: Build and Setup Pipeline

on:
  workflow_dispatch: # Trigger manually on demand

jobs:
  build:
    runs-on: [self-hosted, Librechat] # Use your self-hosted runner with the name Librechat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build data provider
        run: npm run build:data-provider

      - name: Build MCP
        run: npm run build:mcp

      - name: Navigate to client folder and build client
        run: |
          cd client
          npm run build

      - name: Copy .env.example to .env
        run: cp .env.example .env
